### ISSUE TITLE
Panasonic - Unexpected error creating device.

### ISSUE THREAD

**Issue by GigiTax** [sockless-coding/panasonic_cc#195] opened 2024-06-20 07:38 UTC
Hi,
I tried to reconnect my AC to homeassistant but iI received this error: Unexpected error creating device.

Does anyone have idea how to solve this problem?

luigi

**Comment by Faceless3882** [comment] 2024-06-20 11:03
This is a duplicate report see earlier logged issue. It's a known problem and actively being worked on.

**Comment by GigiTax** [comment] 2024-06-20 13:03
> This is a duplicate report see earlier logged issue. It's a known problem and actively being worked on.

Ok. sorry

thanks

gigi

**Comment by codyc1515** [comment] 2024-06-20 21:18
Duplicate of #194

**Comment by kellyatkinson** [comment] 2024-06-21 22:26
@GigiTax can you please mark this issue as closed so the community can focus on fixes? Cheers!

**Comment by sockless-coding** [comment] 2024-06-22 06:09
Duplicate / fixed

**Closed by sockless-coding** 2024-06-22 06:09 UTC
