### ISSUE TITLE
Error after updating to HA 2023.7.0

### ISSUE THREAD

**Issue by robinostlund** [sockless-coding/panasonic_cc#114] opened 2023-07-06 06:33 UTC
2023-07-06 08:32:21.862 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up panasonic_cc platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 361, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 504, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 788, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1005, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 742, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 809, in _async_write_ha_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 748, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/config/custom_components/panasonic_cc/sensor.py", line 142, in state
    return round(self._api.daily_energy,2)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: type NoneType doesn't define __round__ method

**Comment by bakoscsaba** [comment] 2023-07-07 06:50
The issue is present on HA 2023.7.1 as well.
I have 3 devices and usually 1 or 2 of them becomes unavailable after HA is restarted.

After updating to HA 2023.7.0 and after several restarts it managed to find all 3 devices but it seems totally random after every restart which one of them becomes unavailable.

**Comment by elninosi** [comment] 2023-07-07 06:51
I can confirm this behavio @bakoscsaba. Same issue on my side.

**Comment by nicx** [comment] 2023-07-07 07:36
confirmed... 1 or two out of three devices become unavailable after HA restart. When removing and configuring the integration completely new, all three devices are working. after the next restart, same behavior: 1 or 2 devices become unavailable.

**Comment by Herbi-1966** [comment] 2023-07-07 15:48
Unfortunately - same here 🤔

**Comment by rleongcs** [comment] 2023-07-07 17:54
Same here for 2023.7.1. 2 out of 2 are unavailable now.

**Comment by MagnusHass** [comment] 2023-07-07 18:18
Same for me after updating 2023.7.1 my AC unavailable after most reboots, but works sometimes….

**Comment by erikaugl** [comment] 2023-07-07 20:24
Same here, I have 1 outdoor unit connected to two indoor units. One is constantly unavailable.

**Comment by rleongcs** [comment] 2023-07-08 06:03
> Same here for 2023.7.1. 2 out of 2 are unavailable now.

After few reboots, 1 out of 2 working.

**Comment by jwinterton** [comment] 2023-07-08 06:35
Ditto same issue after update to 2023.7.1

**Comment by TimBE1989** [comment] 2023-07-08 08:54
Same issue here.

**Comment by herky999** [comment] 2023-07-09 09:46
I think it has nothing to do with the HA version, but the problem is from Panasonic's side with the newer version of the app

Home Assistant 2023.5.4
Supervisor 2023.07.1
Operating System 10.1

Update for sensor.klima_spalna_daily_energy fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 554, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 779, in async_device_update
    await self.async_update()
  File "/config/custom_components/panasonic_cc/sensor.py", line 164, in async_update
    await self._api.update_energy()
  File "/config/custom_components/panasonic_cc/panasonic.py", line 70, in update_energy
    await self.do_update_energy()
  File "/config/custom_components/panasonic_cc/panasonic.py", line 133, in do_update_energy
    c_energy = data['parameters']['energyConsumption']
KeyError: 'energyConsumption'

**Comment by Herbi-1966** [comment] 2023-07-09 10:56
> I think it has nothing to do with the HA version, but the problem is from Panasonic's side with the newer version of the app
> 
> Home Assistant 2023.5.4 Supervisor 2023.07.1 Operating System 10.1
> 
> Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 554, in async_update_ha_state await self.async_device_update() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 779, in async_device_update await self.async_update() File "/config/custom_components/panasonic_cc/sensor.py", line 164, in async_update await self._api.update_energy() File "/config/custom_components/panasonic_cc/panasonic.py", line 70, in update_energy await self.do_update_energy() File "/config/custom_components/panasonic_cc/panasonic.py", line 133, in do_update_energy c_energy = data['parameters']['energyConsumption'] KeyError: 'energyConsumption'

Maybe it could be a timing problem?

**Comment by galletn** [comment] 2023-07-09 12:30
After a full restart (OS) of HA it was resolved for me.

**Comment by Herbi-1966** [comment] 2023-07-09 14:36
> After a full restart (OS) of HA it was resolved for me.

Hi, how many indoor/outdoor units do you run? What about a second, third () HA restart?
In my case, randomly 2-3 out of  6 indoor AC's are not recognized (2 outdoor units).

**Comment by herky999** [comment] 2023-07-09 17:15
> After a full restart (OS) of HA it was resolved for me.

I can confirm, a full OS restart helped me, thanks

**Comment by herky999** [comment] 2023-07-09 17:39
> After a full restart (OS) of HA it was resolved for me.

After full restart OS is ok, thanks

**Comment by Herbi-1966** [comment] 2023-07-09 18:22
Unfortunately even a complete shutdown and restart of my NUC, running HAssOS, didn't help in my case...

**Comment by nicx** [comment] 2023-07-09 18:44
a complete shutdown/restart helps not in my case.

**Comment by Herbi-1966** [comment] 2023-07-10 15:41
Dear all,

a hint from @aceindy (thank you very much!) in the Homeassistant 'Panasonic Comfort Cloud' community made it for me:

Delete the integration and re-install it.

And all works fine again! :-)

Regards
Herbi

**Comment by nicx** [comment] 2023-07-10 15:45
no, doesnt help here neither. its the same as a new reconfiguration: it works only one time, after a restart the problem reappears.

**Comment by Herbi-1966** [comment] 2023-07-10 16:35
Just checked it with a full (system) restart and the integration 'survived' -strange...

**Comment by nicx** [comment] 2023-07-10 16:48
i thinks it has not only to do with the integration, but also with the panasonic server side. maybe a combination. sometimes a fresh reboot or reinstallation helps, sometimes not. sometimes after a ha restart some devices are failing, sometimes not.

**Comment by Herbi-1966** [comment] 2023-07-10 16:56
I can well imagine that, maybe a timing problem. The Panasonic server has delays, the integration queries are coming too quickly.
I will watch...

**Comment by ParalaX002** [comment] 2023-07-11 06:29
I have the same issue and restart don't help. However, disabling the daily energy sensor solve the issue. But it would be nice to be able to have those sensor.

**Comment by krism23** [comment] 2023-07-11 09:23
> I have the same issue and restart don't help. However, disabling the daily energy sensor solve the issue. But it would be nice to be able to have those sensor.

Disable Daily Energy  + restart fixed. Hopefully, this can be fixed

**Comment by bakoscsaba** [comment] 2023-07-14 15:47
Disabling Daily Energy didn't help me. After restart 2 of 3 or 1 of 3 devices are unavailable.
I also tried disabling Current Power and Outside Temperature sensors but still behaves the same.

I'm on HA 2023.7.2

**Comment by Herbi-1966** [comment] 2023-07-15 06:28
Did you try to delete and reinstall the Integration?

**Comment by bakoscsaba** [comment] 2023-07-15 12:33
My bad... I disabled the entities one by one. If daily energy is disabled from the configuration menu it works.
Of course it would be very nice to have energy info back.

As workaround would it work to create daily energy as a separate integration?

**Comment by progamer562** [comment] 2023-07-16 12:53
same here

**Comment by kongjudas** [comment] 2023-07-20 20:14
The Panasonic units doesn’t really give reliable consumption data, so you have to take it with a pitch of salt. The daily seems trustworthy but the power sensor is just a random number generator.

**Comment by nicx** [comment] 2023-07-21 05:46
so is there currently any reliable solution to this problem or do we need to wait for a bugfix? :)

**Comment by wvergouwenavular** [comment] 2023-07-21 07:46
> The Panasonic units doesn’t really give reliable consumption data, so you have to take it with a pitch of salt. The daily seems trustworthy but the power sensor is just a random number generator.

Did you check this with a power meter? Or how do you know it's unreliable?

**Comment by wvergouwenavular** [comment] 2023-07-21 07:47
Same problem here, after restarting a couple of times my Panasonic units are available, but the power sensors are not working

**Comment by nicx** [comment] 2023-07-21 07:55
> so is there currently any reliable solution to this problem or do we need to wait for a bugfix? :)

just to be clear: I am not talking about a "reliable power consumption solution", but about a reliable HA integration itself without the problem of missing indoor units.
For me the Panasonic integrated power consumption meter is enough. And this, by the way, does not work unreliably but may be inaccurate. 

So don't mix up the "problems":

1. The HA integration is not working reliable anymore since some HA versions. Indoor units are missing (sometimes).
2. The integrated power sensors may be inaccurate.

In this issue we are talking about the 1. problem. Please open up another issue or discussion for the second "problem". thank you :)

**Comment by sockless-coding** [comment] 2023-07-21 08:08
Sorry for not having replied earlier (newborn baby). 
The main problem is the Panasonic cloud servers not responding correctly, the reason restarting HA sometimes fixes the system is that they have multiple servers and using DNS load balancing. `accsmart.panasonic.com` points to an AWS address that has at least 2 different IPs.
This also causes a problem if the devices themselves are connected to a different server than HA, since the synchronization between the servers does not seem to be done in real time.

Regarding the setup problem, it's usually caused by the energy request timing out or failing in some way.

**Comment by kongjudas** [comment] 2023-07-21 09:16
> Did you check this with a power meter? Or how do you know it's unreliable?

If you compare power vs. energy, power is updating too slow to make a correct reading. Due to lack of English competence, I used the wrong term and meant inaccurate, not unreliable. I

> So don't mix up the "problems":

I'm just stating that the power entity is not really worth a lot. It's the API that's slow, not the integration. If you check the app, it's close to useless there too. No harm intended :)

**Comment by jwinterton** [comment] 2023-07-22 19:42
Would it help if one had a local DNS you could use it to overload accsmart.panasonic.com to point to just one of those IP's?

**Comment by togume** [comment] 2023-07-26 14:01
Confirming that CC itself is having connectivity issues - it happens with the iOS Comfort Cloud app, HomeBridge integration, and now finding it here when I'm adding HA to this setup.

I've started a support ticket at https://panasonic.freshdesk.com/en/support/home to see if we can get some traction.

**Comment by togume** [comment] 2023-07-26 18:44
Update - I was able to get things working again by going into the Comfort Cloud app, deleting the device from the account. That logged me out, and then asked me to accept some privacy things. After that I re-added the device, and it's working well again.

**Comment by jeroenvdd** [comment] 2023-07-30 09:58
Same behaviour here sometimes 2 units unavailbale sometimes one... hopefully this gets mended soon worked great in the past :)

**Comment by wvergouwenavular** [comment] 2023-08-01 10:57
> Confirming that CC itself is having connectivity issues - it happens with the iOS Comfort Cloud app, HomeBridge integration, and now finding it here when I'm adding HA to this setup.
> 
> I've started a support ticket at https://panasonic.freshdesk.com/en/support/home to see if we can get some traction.

Any update on this?

**Comment by raczgy** [comment] 2023-08-02 06:58
Unfortunately I have the same issue here. 
Every HA restart causing random number of devices became unavailable.
Would be glad to have some update on this.

**Comment by b1ggi** [comment] 2023-08-02 12:17
> Would it help if one had a local DNS you could use it to overload accsmart.panasonic.com to point to just one of those IP's?

i will try that out with my pihole installation tomorrow, override pointing  to one of the ips

CNAME accsmart.panasonic.com ->  e024-alb-rac-web-prd-1578900232.ap-northeast-1.elb.amazonaws.com
e024-alb-rac-web-prd-1578900232.ap-northeast-1.elb.amazonaws.com -> 54.95.46.69 AND 43.207.244.144

no AAAA ipv6 adresses

**Comment by nicx** [comment] 2023-08-02 12:29
I have 3 indoor units and did some tests regarding DNS ant the 2 IPs of Panasonic:

When using the IP 54.95.46.69 its always number 1 of my indoor unit working, the other 2 are not working.
When using the IP 43.207.244.144 its the other way around, so unit number 2 and 3 are working, unit 1 not.

In conclusion it seems that the unit itself is registered to only one Panasonic IP, and it depends on the IP which is HA using/connecting to, which units are working. There seems a "synchronization" problem on Panasonic side.

As a next step I will try to deregister the unit 1 and reregister it hopefully to the other IP, so that all 3 units are geeisteres tat the same IP of Panasonic. Hopefully this works...

**Comment by togume** [comment] 2023-08-03 13:41
Update from my end: after unregistering/deleting the device from ComfortCloud, deleting the integration from HA, re-adding device to ComfortCloud, re-adding to HA everything has been rock solid.

**Comment by togume** [comment] 2023-08-03 14:25
1 Panasonic unit, no DNS changes, HA and HomeKit. With Rock Solid I mean that I went from it stopped working altogether on the app/HA/Homebridge to zero failed requests since deleting/re-adding last week. I've restarted HA a handful of times since.

Something that was interesting was that once I deleted the device from CC, it logged me out and asked me to accept some agreement. The word from the Panasonic rep is that devices added before some time are failing.

Have you all tried deleting ALL the devices in CC, logging out, logging back in (seeing if that agreement pops up), and re adding?

**Comment by nicx** [comment] 2023-08-03 14:37
> Setup: 1 Panasonic unit, no DNS changes, HA and HomeKit, running via VBox on MacOS home server, Nest Wifi. With Rock Solid I mean that I went from it stopped working altogether on the app/HA/Homebridge to zero failed requests since deleting/re-adding last week. I've restarted HA a handful of times since.
> 
> Something that was interesting was that once I deleted the device from CC, it logged me out and asked me to accept some agreement. The word from the Panasonic rep is that devices added before some time are failing.
> 
> Have you all tried deleting ALL the devices in CC, logging out, logging back in (seeing if that agreement pops up), and re adding?

yes I did. Did not help. Your setup is different, the others including myself do have multiple internal units. So it seems that you had another problem not described here in this issue ;)

**Comment by mgaeremynck** [comment] 2023-08-06 13:51
Any progress with this issue, same behaviour at my place with 6 units

**Comment by wvergouwenavular** [comment] 2023-08-08 06:26
After restarting home assistant a couple of times both my panasonic units were available, however, the energy sensors don't report any values anymore..

**Comment by b1ggi** [comment] 2023-08-08 08:36
I couldnt get it working reliable with forcing either ip address

**Comment by nicx** [comment] 2023-08-10 08:01
with this bugfix it works reliable again for me since 3 days now:

https://github.com/sockless-coding/panasonic_cc/pull/116

**Comment by rleongcs** [comment] 2023-08-10 08:07
@nicx How do I update the integration?

**Comment by nicx** [comment] 2023-08-10 08:53
@rleongcs I just downloaded the update file and copied it over the old file in my custom_integrations directory. ;)

**Comment by rleongcs** [comment] 2023-08-11 16:10
Confirmed it is fine after following @nicx suggestion. Thanks.

Now with every restart, both my aircons are available except the Daily Energy is not available.

**Comment by nicx** [comment] 2023-08-11 17:34
> Now with every restart, both my aircons are available except the Daily Energy is not available.

hm... in my case the daily energy sensor is working without problems, too. have you enabled it in the integration configuration?

**Comment by rleongcs** [comment] 2023-08-12 18:30
> > Now with every restart, both my aircons are available except the Daily Energy is not available.
> 
> hm... in my case the daily energy sensor is working without problems, too. have you enabled it in the integration configuration?

Yes...it is enabled.

**Comment by b1ggi** [comment] 2023-08-16 15:27
can anyone confirm if both ip addresses work reliable again? and if i can remove my local pihole dns entry?

**Comment by nicx** [comment] 2023-08-16 15:31
sure I can confirm with the patch everything is working reliable again. using it for over a week now with daily restarts.

but you need to patch it by yourself because the pull request is not merged yet. dont know when this will happen. @sockless-coding any idea when your newborn will give you time for this? :)

**Comment by elninosi** [comment] 2023-08-16 15:33
I can also confirm that with this fix it works.

**Comment by sockless-coding** [comment] 2023-08-16 19:58
I've managed to find some time to merge the pull request and update the manifest. :)
I've created and published v1.0.36 containing these changes.

**Comment by rleongcs** [comment] 2023-08-18 16:51
@sockless-coding Is the below normal? @nicx mentioned his is working. I have updated to the latest version and still the Daily Energy is unavailable. I did try to disable and enable "Enable daily energy sensor" in the Configure menu with restart after enabling/disabling but still does not help.
Thanks.

![image](https://github.com/sockless-coding/panasonic_cc/assets/61628312/c6ad2857-fff0-4cda-b749-666d94e45471)

**Comment by sockless-coding** [comment] 2023-08-20 15:16
I did some testing and the problem is with the Panasonic Servers, the API request to retrieve energy data have a tendency to return `Internal Server Error`. And if that occurs when HA is starting, the sensor doesn't get registered.

**Comment by codyc1515** [comment] 2024-01-09 20:34
This is fixed?

**Comment by progamer562** [comment] 2024-01-09 23:42
yes

**Comment by codyc1515** [comment] 2024-01-10 01:39
Can you please close the issue?

**Closed** 2024-08-06 08:30 UTC
