### ISSUE TITLE
Stop working - error 412

### ISSUE THREAD

**Issue by mkz212** [sockless-coding/panasonic_cc#332] opened 2024-11-05 07:24 UTC
### Checklist

- [X] I have verified that the account and device works in the Comfort Cloud App.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/sockless-coding/panasonic_cc/issues?q=is%3Aissue+label%3A"bug"+)..

### What version of Home Assistant Core?

core-2024.10.4

### Describe the issue

Expected status code '200' but received '412'. 

Expected status code 200, received: 412: {
  "code":41201,
  "message":"Precondition Failed"
}

Panasonic has probably changed the API again?

**Comment by Nilsenhenning** [comment] 2024-11-05 07:49
Same here

**Comment by Pierrefogg** [comment] 2024-11-05 07:54
Same...

**Comment by aceindy** [comment] 2024-11-05 07:55
Already reported here https://github.com/sockless-coding/panasonic_cc/issues/331#issue-2634217829

**Comment by hrrrsn** [comment] 2024-11-05 08:02
I've just had 4 Panasonic units installed today and was looking forward to getting them added to HA :(

```
custom_components.panasonic_cc.pcomfortcloud.exceptions.ResponseError: (get_acc_client_id: Expected status code 200, received: 412: {
  "code":41201,
  "message":"Precondition Failed"
}
```

**Comment by jamesleivers** [comment] 2024-11-05 08:20
Having same issue here :(

**Comment by sockless-coding** [comment] 2024-11-05 09:11
Duplicate of #331

**Closed by sockless-coding** 2024-11-05 09:11 UTC
Labels: bug

**Comment by kelmcw** [comment] 2024-11-06 05:24
Same here too

**Comment by nosek88** [comment] 2024-11-06 17:45
same :(
