### ISSUE TITLE
every Minute calling to accsmart.panasonic.com

### ISSUE THREAD

**Issue by opetergmxnet** [sockless-coding/panasonic_cc#89] opened 2022-09-04 12:37 UTC
Integration is calling every Minute to this address, but AC Device itself has no power. I do not like this.

2022-09-04 14:33:57 | A | accsmart.panasonic.com |
2022-09-04 14:32:57 | A | accsmart.panasonic.com |

and so on...

**Comment by FastLaneJB** [comment] 2022-09-22 20:47
I've had to turn this component off as when I have it on the Comfort Cloud app on my phone returns an Internal Server Error when trying to log in. The moment I stop the this component on Home Assistant (That's no longer working for me) I can log in and use the app on my phone.

I think Panasonic have put something in their end to block you logging in when this is happening because it's maybe flooding their servers.

**Comment by macflyhub** [comment] 2022-09-22 22:07
I have had this issue and could not figure out what on earth was going on.

**Comment by sockless-coding** [comment] 2022-09-23 15:59
Are you using the same user for both the app and Home Assistance? 
If so, I recommend that you create a separate account for HA. Panasonic only allows you to be logged in on one device at the time, so if you try to log in on the app HA will have to reconnect and when it does, it will kick you from the app.

**Comment by opetergmxnet** [comment] 2022-09-23 16:35
I'm not using the app at all. Regards.

Am 23. September 2022 17:59:26 schrieb Jimmy Everling
***@***.***>:

**Comment by sockless-coding** [comment] 2022-09-23 17:24
@opetergmxnet the integration is call that address to fetch the status of the device. It's the Panasonic API endpoint, they do not provide local access. Also, if your device is offline, why do you have the integration active? 
The integration needs to probe the API to get the device status.

**Comment by opetergmxnet** [comment] 2022-09-23 19:00
I do know that it's trying to fetch the status of the device. But maybe not
that many times.
 I cut the mains of my AC when not in use. And I do not want to enable or
disable the integration manually everytime I switch on or off mains of my AC.

Am 23. September 2022 19:24:44 schrieb Jimmy Everling
***@***.***>:

**Comment by FastLaneJB** [comment] 2022-10-02 23:25
> Are you using the same user for both the app and Home Assistance? If so, I recommend that you create a separate account for HA. Panasonic only allows you to be logged in on one device at the time, so if you try to log in on the app HA will have to reconnect and when it does, it will kick you from the app.

I do have a separate account as I use the app on my mobile also. It worked fine for years but recently when Home Assistant is running, it doesn't work but also my Comfort Cloud doesn't work either. I'll turn it back on and see if it causes the same issues again.

**Comment by codyc1515** [comment] 2022-10-10 00:31
Not sure what you think the issue is here. The integration must "poll" Panasonic's servers (which it is doing periodically) as Panasonic do not "push" updates. You may, for example, use the app or remote to turn on or change the status of the AC which this integration must poll the server in know about in order to those changes.

**Comment by opetergmxnet** [comment] 2022-10-10 06:14
Yes I understood.

If I'm not using the app at all, only ha, there might be a way not to poll
all the time, only if device is switched on. That's my idea.

Am 10. Oktober 2022 02:31:32 schrieb codyc1515 ***@***.***>:

**Comment by opetergmxnet** [comment] 2022-10-10 09:29
That's what it is then... thank you.

Am 10. Oktober 2022 09:11:35 schrieb codyc1515 ***@***.***>:

**Comment by codyc1515** [comment] 2024-01-09 20:53
May be resolved by #152.

**Closed** 2024-01-10 19:50 UTC
